version: 2
jobs:
  build:
    working_directory: ~/wopinator
    docker:
      - image: kapost/ruby:2.4.3-node-6.11.5
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Rspec
          command: bundle exec rspec --color --format documentation --require spec_helper spec
